<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<title>Loading and preprocessing the data</title>

<script type="text/javascript">
window.onload = function() {
  var imgs = document.getElementsByTagName('img'), i, img;
  for (i = 0; i < imgs.length; i++) {
    img = imgs[i];
    // center an image if it is the only element of its parent
    if (img.parentElement.childElementCount === 1)
      img.parentElement.style.textAlign = 'center';
  }
};
</script>





<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 13px;
}

body {
  max-width: 800px;
  margin: auto;
  padding: 1em;
  line-height: 20px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 {
   font-size:2.2em;
}

h2 {
   font-size:1.8em;
}

h3 {
   font-size:1.4em;
}

h4 {
   font-size:1.0em;
}

h5 {
   font-size:0.9em;
}

h6 {
   font-size:0.8em;
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre, img {
  max-width: 100%;
}
pre {
  overflow-x: auto;
}
pre code {
   display: block; padding: 0.5em;
}

code {
  font-size: 92%;
  border: 1px solid #ccc;
}

code[class] {
  background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * {
      background: transparent !important;
      color: black !important;
      filter:none !important;
      -ms-filter: none !important;
   }

   body {
      font-size:12pt;
      max-width:100%;
   }

   a, a:visited {
      text-decoration: underline;
   }

   hr {
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote {
      padding-right: 1em;
      page-break-inside: avoid;
   }

   tr, img {
      page-break-inside: avoid;
   }

   img {
      max-width: 100% !important;
   }

   @page :left {
      margin: 15mm 20mm 15mm 10mm;
   }

   @page :right {
      margin: 15mm 10mm 15mm 20mm;
   }

   p, h2, h3 {
      orphans: 3; widows: 3;
   }

   h2, h3 {
      page-break-after: avoid;
   }
}
</style>



</head>

<body>
<h2>Loading and preprocessing the data</h2>

<h3>Library dependencies</h3>

<pre><code class="r">library(lubridate)
</code></pre>

<pre><code>## 
## Attaching package: &#39;lubridate&#39;
</code></pre>

<pre><code>## The following object is masked from &#39;package:base&#39;:
## 
##     date
</code></pre>

<pre><code class="r">library(ggplot2)
library(plyr);
</code></pre>

<pre><code>## 
## Attaching package: &#39;plyr&#39;
</code></pre>

<pre><code>## The following object is masked from &#39;package:lubridate&#39;:
## 
##     here
</code></pre>

<pre><code class="r">library(dplyr)
</code></pre>

<pre><code>## 
## Attaching package: &#39;dplyr&#39;
</code></pre>

<pre><code>## The following objects are masked from &#39;package:plyr&#39;:
## 
##     arrange, count, desc, failwith, id, mutate, rename, summarise,
##     summarize
</code></pre>

<pre><code>## The following objects are masked from &#39;package:lubridate&#39;:
## 
##     intersect, setdiff, union
</code></pre>

<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag
</code></pre>

<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union
</code></pre>

<h3>Load raw data</h3>

<p>Load raw data from <code>activity.csv</code></p>

<pre><code class="r">activityRawSet &lt;- read.csv(&quot;activity.csv&quot;,sep = &quot;,&quot;, na.strings = &quot;NA&quot;, stringsAsFactors = FALSE)

head(activityRawSet)
</code></pre>

<pre><code>##   steps       date interval
## 1    NA 2012-10-01        0
## 2    NA 2012-10-01        5
## 3    NA 2012-10-01       10
## 4    NA 2012-10-01       15
## 5    NA 2012-10-01       20
## 6    NA 2012-10-01       25
</code></pre>

<h3>Prepare data</h3>

<p>Create a data frame from <code>activityRawSet</code> and mutate date column as date object</p>

<pre><code class="r">activitySet_df &lt;- tbl_df(activityRawSet)
# add mutate date as date object
activitySet_df &lt;- mutate(activitySet_df, date = as.Date(activitySet_df$date, &quot;%Y-%m-%d&quot;) )
</code></pre>

<p>create data frame grouped by date and add <code>count_steps</code> variable including NA values.</p>

<pre><code class="r"># create df group by date
activity_steps_taken &lt;- activitySet_df %&gt;%
    group_by(date) %&gt;%
    summarize(count_steps = sum(steps,na.rm=TRUE)
    )
</code></pre>

<p>Part of data is shown as follow:</p>

<pre><code class="r"># show data
activity_steps_taken
</code></pre>

<pre><code>## # A tibble: 61 x 2
##          date count_steps
##        &lt;date&gt;       &lt;int&gt;
##  1 2012-10-01           0
##  2 2012-10-02         126
##  3 2012-10-03       11352
##  4 2012-10-04       12116
##  5 2012-10-05       13294
##  6 2012-10-06       15420
##  7 2012-10-07       11015
##  8 2012-10-08           0
##  9 2012-10-09       12811
## 10 2012-10-10        9900
## # ... with 51 more rows
</code></pre>

<h2>What is mean total number of steps taken per day?</h2>

<p>The mean and median of total steps taken per day were calculated, using <code>mean()</code> and <code>median()</code> functions with <code>activity_steps_taken$count_steps</code> as parameter including observations with <code>NA</code> values.</p>

<pre><code class="r">activity_mean &lt;- mean(activity_steps_taken$count_steps)
activity_median &lt;- median(activity_steps_taken$count_steps)
</code></pre>

<p>The mean total number of steps taken per day is:  <strong><code>9354.23</code>** and the median total number of steps taken per day is: **<code>10395</code></strong>.</p>

<p><em>Figure 1</em>, shows the histogram of the total number of steps taken each day including its total mean and median values represented by red and blue doted lines respectively.</p>

<pre><code class="r"># Generate histogram
hist(activity_steps_taken$count_steps, breaks=25, main=&quot;Figure 1: Histogram of Total Number of Steps in each Day&quot;, xlab=&quot;Total Steps [count_steps]&quot;)
rug(activity_steps_taken$count_steps)
abline(v = activity_mean, col = &quot;red&quot;, lwd = 1, lty = 2)
abline(v = activity_median, col = &quot;blue&quot;, lwd = 1, lty = 2)
text(activity_mean-0.3e3, 8, bquote(bar(x) == .(activity_mean)), col = &quot;red&quot;, srt = 90,cex=0.6)
text(activity_median+0.4e3, 8,  bquote(mu == .(activity_median)), col = &quot;blue&quot;, srt = 90,cex=0.6)
</code></pre>

<p><img src="figure/unnamed-chunk-5-1.png" alt="plot of chunk unnamed-chunk-5"></p>

<h2>What is the average daily activity pattern?</h2>

<p>Grouped dataset by time interval to obtain the total number and average number of steps taken per interval, averaged across all days.</p>

<pre><code class="r"># Avg number of steps grouped by interval
# create count_steps and avg_steps variables 
# include NA values
activity_time &lt;- activitySet_df %&gt;%
    group_by(interval) %&gt;%
    summarize(count_steps = sum(steps,na.rm=TRUE),
              avg_steps = mean(steps,na.rm=TRUE)
    )
</code></pre>

<p>Portion of <code>activity_time</code> dataset </p>

<pre><code>## # A tibble: 288 x 3
##    interval count_steps avg_steps
##       &lt;int&gt;       &lt;int&gt;     &lt;dbl&gt;
##  1        0          91 1.7169811
##  2        5          18 0.3396226
##  3       10           7 0.1320755
##  4       15           8 0.1509434
##  5       20           4 0.0754717
##  6       25         111 2.0943396
##  7       30          28 0.5283019
##  8       35          46 0.8679245
##  9       40           0 0.0000000
## 10       45          78 1.4716981
## # ... with 278 more rows
</code></pre>

<p>The summary of <code>activity_time$avg_steps</code> shows on average the maximum number of steps in the column (<code>Max.</code>) </p>

<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.000   2.486  34.110  37.380  52.830 206.200
</code></pre>

<p>The 5-minute interval that on average, contains the maximum number of steps is calculated as follow:</p>

<pre><code class="r"># Get the index value from the max avg_steps value of activity_time dataset 
# set result to max_interval object
max_interval&lt;-activity_time[which.max(activity_time$avg_steps), ]
max_interval
</code></pre>

<pre><code>## # A tibble: 1 x 3
##   interval count_steps avg_steps
##      &lt;int&gt;       &lt;int&gt;     &lt;dbl&gt;
## 1      835       10927  206.1698
</code></pre>

<p>Across all the days in the dataset, the 5-minute interval of <strong><code>835</code>** minutes , with a total of **<code>10927</code>** steps, on average contains a maximum of **<code>206.17</code></strong> steps.</p>

<p><em>Figure 2</em>, shows the time series plot of the average number of steps taken, including the 5-minute interval that on average, contains the maximum number of steps (Doted red vertical line).</p>

<pre><code class="r">    g2 &lt;- ggplot(activity_time, aes(interval, avg_steps))
    g2 + geom_line() + ggtitle(&quot;Figure 2. Time series plot of the average number of steps taken&quot;) + 

    # Label axis
    xlab(&quot;5  Interval (minutes)&quot;) +  ylab(&quot;Avg. Activity (steps)&quot;) + 


    # Add doted lines
    geom_vline(aes(xintercept=max_interval$interval), color=&quot;red&quot;, linetype=&quot;dashed&quot;, size=1/3) +

    geom_hline(aes(yintercept=max_interval$avg_steps), color=&quot;red&quot;, linetype=&quot;dashed&quot;, size=1/3) + 

    # Add label to doted lines
    geom_text(aes(x=550, label=paste(&quot; Max. Steps =&quot;, round(max_interval$avg_steps, digits=2),  sep=&quot; &quot;), y=max_interval$avg_steps-0.1e2), colour=&quot;red&quot;, size=3) + 

    geom_text(aes(x=max_interval$interval+0.3e2, label=paste(&quot; 5 min Interval =&quot;, round(max_interval$interval, digits=2),  sep=&quot; &quot;), y=100), colour=&quot;red&quot;, angle=90, size=3) + theme_classic()
</code></pre>

<p><img src="figure/g2-1.png" alt="plot of chunk g2"></p>

<h2>Imputing missing values</h2>

<p>Note that there are a number of days/intervals where there are missing values (coded as 𝙽𝙰). The presence of missing days may introduce bias into some calculations or summaries of the data. The total number of observations containing missing values are calculated as follow.</p>

<pre><code class="r">activity_count_na_values &lt;- sum(is.na(activityRawSet$steps))
</code></pre>

<p>The total number of observations containing missing values in steps variable is <strong><code>2304</code></strong> </p>

<p>The strategy for filling in all of the missing values in the dataset is replacing NA values with the mean of 5-minute time interval and create a new dataset <code>activity_fill_na</code> that is equal to the original dataset <code>activitySet_df</code> but with the missing data filled in.</p>

<pre><code class="r"># Group activitySet_df by interval
# Replace NA values in steps variable with the mean() by interval
activity_fill_na &lt;- activitySet_df %&gt;%
    group_by(interval)  %&gt;%
    mutate(steps= ifelse(is.na(steps), mean(steps, na.rm=TRUE), steps))
</code></pre>

<p>Check  <code>activity_fill_na</code> dataset with 0 <code>NA</code> values</p>

<pre><code>##    steps     date interval 
##        0        0        0
</code></pre>

<p>Portion of <code>activity_fill_na</code> dataset after imputing NA values</p>

<pre><code>## Source: local data frame [17,568 x 3]
## Groups: interval [288]
## 
## # A tibble: 17,568 x 3
##        steps       date interval
##        &lt;dbl&gt;     &lt;date&gt;    &lt;int&gt;
##  1 1.7169811 2012-10-01        0
##  2 0.3396226 2012-10-01        5
##  3 0.1320755 2012-10-01       10
##  4 0.1509434 2012-10-01       15
##  5 0.0754717 2012-10-01       20
##  6 2.0943396 2012-10-01       25
##  7 0.5283019 2012-10-01       30
##  8 0.8679245 2012-10-01       35
##  9 0.0000000 2012-10-01       40
## 10 1.4716981 2012-10-01       45
## # ... with 17,558 more rows
</code></pre>

<p>Summary to compare <code>activity_steps_taken_im</code> dataset with imputed missing values and the original dataset <code>activity_steps_taken</code> </p>

<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##       0    6778   10400    9354   12810   21190
</code></pre>

<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##      41    9819   10770   10770   12810   21190
</code></pre>

<p><em>Figure 3</em>, Shows Histogram of the total number of steps taken each day after missing values are imputed including its total mean and median values represented by red and blue doted lines respectively. In this case after imputed <strong><code>2304</code>** missing values generates a slight increase in the values of the average and the median (compares original dataset with NA values) which causes both values, the mean and the median to be equals **<code>10776.19</code></strong>.</p>

<pre><code class="r"># Generate histogram
hist(activity_steps_taken_im$count_steps, breaks=25, main=&quot;Figure 3: Histogram of Total Number of Steps in each Day \n With Imputing Missing Values&quot;, xlab=&quot;Total Steps [count_steps]&quot;)
rug(activity_steps_taken_im$count_steps)
abline(v = activity_mean_imp, col = &quot;red&quot;, lwd = 1, lty = 2)
abline(v = activity_median_imp, col = &quot;blue&quot;, lwd = 1, lty = 2)
text(activity_mean_imp-0.3e3, 8, bquote(bar(x) == .(activity_mean_imp)), col = &quot;red&quot;, srt = 90,cex=0.6)
text(activity_median_imp+0.5e3, 8,  bquote(mu == .(activity_median_imp)), col = &quot;blue&quot;, srt = 90,cex=0.6)
</code></pre>

<p><img src="figure/unnamed-chunk-13-1.png" alt="plot of chunk unnamed-chunk-13"></p>

<p><em>Figure 4</em>, Shows two histograms to compare the total number of steps taken each day, the first one shows the distribution before imputing and the second one shows the distribution after imputing missing values.</p>

<pre><code class="r">#Generate Histograms
par(mfrow = c(2, 1), oma = c(2, 2, 2, 2) , mar = c(2, 2, 2, 2))

# Generate histogram without imputing values (Original)
hist(activity_steps_taken$count_steps, breaks=25, main=&quot;Dataset Before Imputing Missing Values&quot;, xlab=&quot;Total Steps [count_steps]&quot;)
rug(activity_steps_taken$count_steps)
abline(v = activity_mean, col = &quot;red&quot;, lwd = 1, lty = 2)
abline(v = activity_median, col = &quot;blue&quot;, lwd = 1, lty = 2)
text(activity_mean-0.3e3, 8, bquote(bar(x) == .(activity_mean)), col = &quot;red&quot;, srt = 90,cex=0.6)
text(activity_median+0.4e3, 8,  bquote(mu == .(activity_median)), col = &quot;blue&quot;, srt = 90,cex=0.6)

# Generate histogram with imputing values
hist(activity_steps_taken_im$count_steps, breaks=25, main=&quot;Dataset After Imputing Missing Values&quot;, xlab=&quot;Total Steps [count_steps]&quot;)
rug(activity_steps_taken_im$count_steps)
abline(v = activity_mean_imp, col = &quot;red&quot;, lwd = 1, lty = 2)
abline(v = activity_median_imp, col = &quot;blue&quot;, lwd = 1, lty = 2)
text(activity_mean_imp-0.3e3, 8, bquote(bar(x) == .(activity_mean_imp)), col = &quot;red&quot;, srt = 90,cex=0.6)
text(activity_median_imp+0.4e3, 8,  bquote(mu == .(activity_median_imp)), col = &quot;blue&quot;, srt = 90,cex=0.6)

title(&quot;Figure 4: Histogram of Total Number of Steps in each Day &quot;, outer=TRUE)
</code></pre>

<p><img src="figure/unnamed-chunk-14-1.png" alt="plot of chunk unnamed-chunk-14"></p>

<h2>Are there differences in activity patterns between weekdays and weekends?</h2>

<p>The summary of mean and median by group (weekends and weekdays) is as follow:</p>

<pre><code>##   day_type activity_mean
## 1  Weekend      42.36640
## 2  Weekday      35.61058
</code></pre>

<pre><code>##   day_type activity_median
## 1  Weekend        32.33962
## 2  Weekday        25.80314
</code></pre>

<p><em>Figure 5</em>, Shows Panel plot comparing the average number of steps taken per 5-minute interval across weekdays and weekends including the mean for every group.</p>

<p>The number of steps taken per 5-minute shows that on average, there is more activity on weekends (<strong>42.37 Steps</strong>)  than weekdays (<strong>35.61 Steps</strong>). </p>

<p>Activity during weekdays starts much earlier than on weekends. On weekdays the activity take place between 8:30 and 9:30 in the morning surpassing its own average during this period and although during the weekends begins activity around 8.30 only it is observed that it surpasses its own average around the 09:30</p>

<p><img src="figure/unnamed-chunk-17-1.png" alt="plot of chunk unnamed-chunk-17"></p>

</body>

</html>
